version: "3.9"
services:
  nextjs:
    build:
      context: ./docker/nextjs
    command: node_modules/.bin/next dev
    volumes:
      - ./docker/nextjs/src:/home/node:rw
      - /home/node/node_modules
    ports:
      - "3000:3000"